//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightMove.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RightMove.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;code&quot;:1,&quot;outcode&quot;:&quot;AB10&quot;},{&quot;code&quot;:2,&quot;outcode&quot;:&quot;AB11&quot;},{&quot;code&quot;:3,&quot;outcode&quot;:&quot;AB12&quot;},{&quot;code&quot;:4,&quot;outcode&quot;:&quot;AB13&quot;},{&quot;code&quot;:5,&quot;outcode&quot;:&quot;AB14&quot;},{&quot;code&quot;:6,&quot;outcode&quot;:&quot;AB15&quot;},{&quot;code&quot;:7,&quot;outcode&quot;:&quot;AB16&quot;},{&quot;code&quot;:8,&quot;outcode&quot;:&quot;AB21&quot;},{&quot;code&quot;:9,&quot;outcode&quot;:&quot;AB22&quot;},{&quot;code&quot;:10,&quot;outcode&quot;:&quot;AB23&quot;},{&quot;code&quot;:11,&quot;outcode&quot;:&quot;AB24&quot;},{&quot;code&quot;:12,&quot;outcode&quot;:&quot;AB25&quot;},{&quot;code&quot;:13,&quot;outcode&quot;:&quot;AB30&quot;},{&quot;code&quot;:14,&quot;outcode&quot;:&quot;AB31&quot;},{&quot;code&quot;:15,&quot;outcode&quot;:&quot;AB32&quot;},{&quot;code&quot;:16,&quot;outcode&quot;:&quot;AB33&quot;},{&quot;code&quot;:17,&quot;outcode&quot;:&quot;AB34&quot;},{&quot;code&quot;:18,&quot....
        /// </summary>
        internal static string Outcodes {
            get {
                return ResourceManager.GetString("Outcodes", resourceCulture);
            }
        }
    }
}
